<?php
namespace Steenbag\Tubes\General\Auth;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;

/**
 * invalid authentication request (invalid keyspace, user does not exist, or credentials invalid)
 */
class AuthenticationException extends TException implements JsonSerializable
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'why',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'code',
            'isRequired' => true,
            'type' => TType::I32,
        ),
    );

    /**
     * @var string
     */
    public $why = null;
    /**
     * @var int
     */
    public $code = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'AuthenticationException';
    }


    public function read($input)
    {
        $tmp = $this->_read('AuthenticationException', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('AuthenticationException', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->why === null) {
            throw new TProtocolException('Required field AuthenticationException.why is unset!');
        }
        if ($this->code === null) {
            throw new TProtocolException('Required field AuthenticationException.code is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->why === null) {
            throw new TProtocolException('Required field AuthenticationException.why is unset!');
        }
        if ($this->code === null) {
            throw new TProtocolException('Required field AuthenticationException.code is unset!');
        }
    }

    public function jsonSerialize() {
        $this->_validateForWrite();
        $json = new stdClass;
        if ($this->why !== null) {
            $json->why = (string)$this->why;
        }
        if ($this->code !== null) {
            $json->code = (int)$this->code;
        }
        return $json;
    }
}
