//
// Autogenerated by Ng Thrift Service Command
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
// CHANGES WILL BE OVERWRITTEN THE NEXT TIME THE GENERATOR IS RUN
//

(function () {

  define([{{dependencies}}], function () {
    {{client_name}}.$inject = ['$window', '$q', 'Thrift'];
    function {{client_name}}($window, $q, Thrift) {

      var service = {{public_service_def}};

      return service;

      {{internal_service_def}}

      function getClient() {
        return Thrift.getClient($window.{{thrift_name}}Client, "{{thrift_service_name}}");
      }

    }

    return {{client_name}};
  });

})();
