<?php
namespace Steenbag\Tubes\General\Debug;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;

/**
 * We have died something out on the server and want to send a structured result to the client for easy debugging.
 */
class DieDumpException extends TException implements JsonSerializable
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'json_data',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $json_data = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'DieDumpException';
    }


    public function read($input)
    {
        $tmp = $this->_read('DieDumpException', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('DieDumpException', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->json_data === null) {
            throw new TProtocolException('Required field DieDumpException.json_data is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->json_data === null) {
            throw new TProtocolException('Required field DieDumpException.json_data is unset!');
        }
    }

    public function jsonSerialize() {
        $this->_validateForWrite();
        $json = new stdClass;
        if ($this->json_data !== null) {
            $json->json_data = (string)$this->json_data;
        }
        return $json;
    }
}
