<?php
namespace Steenbag\Tubes\General\Debug;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;

class ServerException extends TException implements JsonSerializable
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'code',
            'isRequired' => true,
            'type' => TType::I32,
        ),
        2 => array(
            'var' => 'message',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'file',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'line',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        5 => array(
            'var' => 'trace',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRUCT,
            'elem' => array(
                'type' => TType::STRUCT,
                'class' => '\Steenbag\Tubes\General\Debug\StackTraceElement',
                ),
        ),
    );

    /**
     * @var int
     */
    public $code = null;
    /**
     * @var string
     */
    public $message = null;
    /**
     * @var string
     */
    public $file = null;
    /**
     * @var int
     */
    public $line = null;
    /**
     * @var \Steenbag\Tubes\General\Debug\StackTraceElement[]
     */
    public $trace = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'ServerException';
    }


    public function read($input)
    {
        $tmp = $this->_read('ServerException', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('ServerException', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->code === null) {
            throw new TProtocolException('Required field ServerException.code is unset!');
        }
        if ($this->message === null) {
            throw new TProtocolException('Required field ServerException.message is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->code === null) {
            throw new TProtocolException('Required field ServerException.code is unset!');
        }
        if ($this->message === null) {
            throw new TProtocolException('Required field ServerException.message is unset!');
        }
    }

    public function jsonSerialize() {
        $this->_validateForWrite();
        $json = new stdClass;
        if ($this->code !== null) {
            $json->code = (int)$this->code;
        }
        if ($this->message !== null) {
            $json->message = (string)$this->message;
        }
        if ($this->file !== null) {
            $json->file = (string)$this->file;
        }
        if ($this->line !== null) {
            $json->line = (int)$this->line;
        }
        if ($this->trace !== null) {
            $json->trace = $this->trace;
        }
        return $json;
    }
}
