<?php
namespace Steenbag\Tubes\General\Debug;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;

class StackTraceElement extends TBase implements JsonSerializable
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'file',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'line',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'function_ref',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        4 => array(
            'var' => 'arguments',
            'isRequired' => false,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
        5 => array(
            'var' => 'class_ref',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'type',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        7 => array(
            'var' => 'object',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $file = null;
    /**
     * @var int
     */
    public $line = null;
    /**
     * @var string
     */
    public $function_ref = null;
    /**
     * @var string[]
     */
    public $arguments = null;
    /**
     * @var string
     */
    public $class_ref = null;
    /**
     * @var string
     */
    public $type = null;
    /**
     * @var string
     */
    public $object = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'StackTraceElement';
    }


    public function read($input)
    {
        return $this->_read('StackTraceElement', self::$_TSPEC, $input);
    }


    public function write($output)
    {
        return $this->_write('StackTraceElement', self::$_TSPEC, $output);
    }


    public function jsonSerialize() {
        $json = new stdClass;
        if ($this->file !== null) {
            $json->file = (string)$this->file;
        }
        if ($this->line !== null) {
            $json->line = (int)$this->line;
        }
        if ($this->function_ref !== null) {
            $json->function_ref = (string)$this->function_ref;
        }
        if ($this->arguments !== null) {
            $json->arguments = $this->arguments;
        }
        if ($this->class_ref !== null) {
            $json->class_ref = (string)$this->class_ref;
        }
        if ($this->type !== null) {
            $json->type = (string)$this->type;
        }
        if ($this->object !== null) {
            $json->object = (string)$this->object;
        }
        return $json;
    }
}
