<?php
namespace Steenbag\Tubes\General\Types;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;

/**
 * Invalid request means that something about the request was invalid.
 */
class InvalidRequestException extends TException implements JsonSerializable
{
    static public $isValidate = true;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'reasons',
            'isRequired' => true,
            'type' => TType::LST,
            'etype' => TType::STRING,
            'elem' => array(
                'type' => TType::STRING,
                ),
        ),
    );

    /**
     * @var string[]
     */
    public $reasons = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'InvalidRequestException';
    }


    public function read($input)
    {
        $tmp = $this->_read('InvalidRequestException', self::$_TSPEC, $input);
        $this->_validateForRead();
        return $tmp;
    }


    public function write($output)
    {
        $this->_validateForWrite();
        return $this->_write('InvalidRequestException', self::$_TSPEC, $output);
    }


    private function _validateForRead() {
        if ($this->reasons === null) {
            throw new TProtocolException('Required field InvalidRequestException.reasons is unset!');
        }
    }

    private function _validateForWrite() {
        if ($this->reasons === null) {
            throw new TProtocolException('Required field InvalidRequestException.reasons is unset!');
        }
    }

    public function jsonSerialize() {
        $this->_validateForWrite();
        $json = new stdClass;
        if ($this->reasons !== null) {
            $json->reasons = $this->reasons;
        }
        return $json;
    }
}
